### ISSUE TITLE
add a DUMP_BUFFER command

### ISSUE THREAD

**Issue by AaronGhost** [google/shadertrap#41]
Buffers can already be compared in a single run using the ASSERT_EQUAL command but it does not permit to save buffer results to compare them across different runs.

While the binary representation could already be useful, a human-readable version would be best for debugging. As the type of the underlying data is bound at buffer creation (and by the underlying interface block in the shader), it could use the format provided at creation to recognize uint, int, etc.. when dumping to the file.

**Comment by afd** [comment]
Good idea to add this command.

I would prefer not to utilise the format that was specified at buffer creation time. It does seem tempting, bu @paulthomson and I feel quite strongly that buffers should be trated as untyped sequences of bytes, and that using types at initialization is just a means of conveniently specifying the initial sequence. I would prefer for DUMP_BUFFER to have syntax for explaining how the buffer should be laid out.

I suggest we have two commands:

```
// Dump "buffer" to "file", in binary form 
DUMP_BUFFER_BINARY BUFFER buffer FILE file
```

and:

```
DUMP_BUFFER_TEXT BUFFER buffer FORMAT format1 format2 ... formatn
```

where each format is one of:

- a quoted string
- type count - i.e., a type followed by the number of things of that type, where type is one of float, int, uint or byte, as in CREATE_BUFFER

Quoted strings will be included in the text output directly. A type with a count will cause the buffer data to be interpreted as that number of things of the given type, which will be emitted separated by spaces.

So, for example, if you had a buffer that represented a struct:

```
struct S {
  float x;
  mat2x2 m;
  int A[8];
}
```

with no padding then you could do:

```
DUMP_BUFFER_TEXT BUFFER my_buf FORMAT float 5 " " int 8
```

to have the numbers associated with the struct fields printed in a space-separated way, or you could do:

```
DUMP_BUFFER_TEXT BUFFER my_buf FORMAT
  "x: " float 1
  "\nm: " float 4
  "\nA: " int 8
```

to have the struct printed with field names.

What do you think?

@asuonpaa I'd also value your opinion.

**Comment by asuonpaa** [comment]
Sounds good to me. To support buffers with offset or padding something like `skip BYTES` might be useful too. For example if you had a vec3 padded to vec4 you could do `"vec3: " float 3 skip 4`.

**Comment by afd** [comment]
Good idea.
