### ISSUE TITLE
Write a series of matrix multiplication examples

### ISSUE THREAD

**Issue by afd** [google/shadertrap#64]
Write ShaderTrap scripts that use compute shaders to perform matrix multiplication.

The purpose of these examples is to provide an interesting set of compute shaders. They do not necessarily need to represent good practice from a performance perspective.

Top-level spec for all examples:

- Inputs: 2 arrays of floating-point data representing the contents of a pair of 16x16 matrices
- Output: 1 array of floating-point data that will represent the 16x16 matrix that results from multiplying these matrices together

- [ ] Version 1:
* Write a sequential matrix multiplication routine, executed by a single invocation

- [ ] Version 2:
* Write a version of 1 where the matrix input data is interpreted as a block-partitioned matrix: four 4x4 matrices rather than a 16x16 array of floats. A single invocation can then compute the product of the matrices using operations on the mat4x4 datatype to multiply sub-matrices.

- [ ] Version 3:
* The same as version 2, but consider the input as a block-partitioned matrix made up of 2x2 matrices instead of 3x3 matrices

- [ ] Version 4:
* Use parallelism. Have a grid of 16x16 invocations and follow an approach like this one for CUDA: https://www.quantstart.com/articles/Matrix-Matrix-Multiplication-on-the-GPU-with-Nvidia-CUDA/

- [ ] Version 5:
* Use parallelism, and also block-partitioned matrices (i.e., combine version 4 with either version 2 or version 3)

- [ ] Version 6:
* Implement matrix multiplication using *shared memory* within a group. There are many articles online about how to do this in CUDA. It should be reasonably straightforward to port them to OpenGL compute shaders.

**Comment by emiljanogj** [comment]
@afd Can I start working on this issue?

**Comment by afd** [comment]
@EGJ1996 Yes - please go ahead!
